// Generated by scripts/brand.py from design-system/tokens.json and .pi/confidentiality.json. Do not edit.
//
// The three level colours, from the dark theme text tokens, because a terminal is dark.
// allow is the lowest level (public), refuse is the highest (restricted) and the glyph colours
// signal-allow and signal-refuse are aliases of those two, which is why a refusal is never
// a fourth red. between carries every level in the middle.

export type Paint = "allow" | "between" | "refuse" | "dim";

export const RGB: Record<Exclude<Paint, "dim">, [number, number, number]> = {
  allow: [79, 201, 138],
  between: [122, 167, 240],
  refuse: [255, 127, 143],
};

/** The 4 bit fallback, for a terminal that does not report truecolor. */
export const BASIC: Record<Exclude<Paint, "dim">, string> = {
  allow: "\x1b[32m",
  between: "\x1b[94m",
  refuse: "\x1b[31m",
};
