#!/usr/bin/env python3
"""Generate every marked surface from the two files that own the facts.

`design-system/tokens.json` owns the look. `.pi/confidentiality.json` owns the levels
and the clearances. Nothing else in this repo may type a hex value or a provider list
by hand.

The design system says the artifact is marked by the system it describes, and that the
band is "read from .pi/confidentiality.json rather than typed". Until this script
existed it was typed, in six places, and the GitHub banner had already drifted: it
still listed five providers and a ladder reading "4 of 5" after `verda` was added.

    python3 scripts/brand.py            # write every generated surface
    python3 scripts/brand.py --check    # exit 1 if a surface is out of date
    python3 scripts/brand.py --list     # what this script owns

Standard library only, like the audit skills. Flattening the two cover SVGs to
outlines needs inkscape (see design-system/components/CoverBanner/README.md); without
it those two files are skipped, everything else still runs, and --check says so.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS_FILE = ROOT / "design-system" / "tokens.json"
POLICY_FILE = ROOT / ".pi" / "confidentiality.json"
STAMP = "Generated by scripts/brand.py from design-system/tokens.json and .pi/confidentiality.json. Do not edit."


# --------------------------------------------------------------------------- model


class Brand:
    """The tokens and the policy, resolved."""

    def __init__(self, tokens: dict, policy: dict) -> None:
        self.tokens = tokens
        self.policy = policy
        self.levels: list[str] = policy["levels"]
        self.providers: dict[str, str] = policy["providers"]
        self._colors = {t["name"]: t["value"] for t in tokens["color"]["tokens"]}
        self.space = {t["name"]: t["value"] for t in tokens["spacing"]["tokens"]}
        self.radius = {t["name"]: t["value"] for t in tokens["radius"]["tokens"]}
        self.shadow = {t["name"]: t["value"] for t in tokens["shadow"]["tokens"]}
        self.families = tokens["type"]["families"]
        self.styles: dict[str, dict] = {}
        for group in tokens["type"]["groups"]:
            for style in group["styles"]:
                self.styles[style["name"]] = {"family": group["family"], **style}

    # tokens

    def color(self, name: str, theme: str = "light") -> str:
        """A colour token, following an alias such as {text-restricted}."""
        value = self._colors[name]
        if isinstance(value, str):
            alias = re.fullmatch(r"\{([a-z0-9-]+)\}", value)
            if not alias:
                return value
            return self.color(alias.group(1), theme)
        return value[theme]

    def color_names(self) -> list[str]:
        return [t["name"] for t in self.tokens["color"]["tokens"]]

    def rgb(self, name: str, theme: str = "light") -> tuple[int, int, int]:
        h = self.color(name, theme).lstrip("#")
        return tuple(int(h[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]

    def px(self, style: str, key: str = "fontSize") -> int:
        return int(str(self.styles[style][key]).removesuffix("px"))

    def font(self, style: str) -> str:
        """The first family of a type style, which is what an SVG or a font URL needs."""
        stack = self.families[self.styles[style]["family"]]
        return stack.split(",")[0].strip().strip('"')

    # policy

    def rank(self, level: str) -> int:
        return self.levels.index(level)

    def cleared(self, level: str) -> list[str]:
        """Providers cleared to read `level`, lowest clearance first, file order within a level."""
        order = list(self.providers)
        return sorted(
            (p for p, c in self.providers.items() if self.rank(c) >= self.rank(level)),
            key=lambda p: (self.rank(self.providers[p]), order.index(p)),
        )

    def at(self, level: str) -> list[str]:
        """Providers whose own clearance is exactly `level`."""
        return [p for p, c in self.providers.items() if c == level]

    def marking(self, level: str) -> str:
        """The marking line a document carries, as in design-system/guidelines/30-github-cover.md."""
        return f"`{level.upper()}` · cleared: {', '.join(self.cleared(level))}"

    def band_right(self, level: str) -> str:
        """The right hand side of a band: who is cleared to see this page."""
        return "CLEARED: " + ", ".join(p.upper() for p in self.cleared(level))

    def workspaces(self) -> list[tuple[str, str]]:
        """Every labelled folder in the repo, as (path relative to root, level)."""
        found = []
        for label in sorted(ROOT.glob("*/*/.confidentiality.json")):
            level = json.loads(label.read_text(encoding="utf-8")).get("level")
            if level in self.levels:
                found.append((label.parent.relative_to(ROOT).as_posix(), level))
        return found


def load() -> Brand:
    return Brand(
        json.loads(TOKENS_FILE.read_text(encoding="utf-8")),
        json.loads(POLICY_FILE.read_text(encoding="utf-8")),
    )


# ----------------------------------------------------------------- generated files


def tokens_css(b: Brand) -> str:
    def block(theme: str, indent: str) -> list[str]:
        return [f"{indent}--{name}: {b.color(name, theme)};" for name in b.color_names()]

    out = [f"/* {STAMP} */", "", ":root {"]
    out += block("light", "  ")
    out.append("")
    for key, stack in b.families.items():
        out.append(f"  --font-{key}: {stack};")
    out.append("")
    for name, value in b.space.items():
        out.append(f"  --{name}: {value};")
    for name, value in b.radius.items():
        out.append(f"  --{name}: {value};")
    for name, value in b.shadow.items():
        out.append(f"  --{name}: {value};")
    out += ["}", "", "/* Screen. The band fills stay dark in both themes, because band-ink is white in both. */"]
    out.append("@media (prefers-color-scheme: dark) {")
    out.append('  :root:not([data-theme="light"]) {')
    out += block("dark", "    ")
    out += ["  }", "}", "", ':root[data-theme="dark"] {']
    out += block("dark", "  ")
    out.append("}")
    return "\n".join(out) + "\n"


def tokens_py(b: Brand) -> str:
    """Constants for the Python surfaces: the report writer, the notebook, any future deck build."""
    levels = json.dumps(b.levels)
    providers = json.dumps(b.providers, indent=4)
    colors = {name: {t: b.color(name, t) for t in ("light", "dark")} for name in b.color_names()}
    ansi = {level: b.rgb(f"text-{level}", "dark") if f"text-{level}" in b._colors else b.rgb("text-confidential", "dark") for level in b.levels}
    out = [
        '"""' + STAMP + '"""',
        "",
        f"LEVELS = {levels}",
        f"PROVIDERS = {providers}",
        "",
        "COLOR = " + json.dumps(colors, indent=4),
        "",
        "SPACE = " + json.dumps(b.space, indent=4),
        "",
        "#: Providers cleared to read each level, lowest clearance first.",
        "CLEARED = " + json.dumps({level: b.cleared(level) for level in b.levels}, indent=4),
        "",
        "#: The marking line a generated document carries.",
        "MARKING = " + json.dumps({level: b.marking(level) for level in b.levels}, indent=4),
        "",
        "#: Terminal truecolor for a level, from the dark theme text tokens.",
        "LEVEL_RGB = " + json.dumps({k: list(v) for k, v in ansi.items()}, indent=4),
        "",
        "",
        "def marking(level: str) -> str:",
        '    """The marking line for a level, or a refusal to mark a level the policy does not know."""',
        "    if level not in MARKING:",
        '        raise ValueError(f"{level!r} is not a level in .pi/confidentiality.json: {LEVELS}")',
        "    return MARKING[level]",
        "",
    ]
    return "\n".join(out)


def brand_ts(b: Brand) -> str:
    """The terminal palette, so the product prints the colours the deck quotes."""
    low, high = b.levels[0], b.levels[-1]
    rgb = {
        "allow": b.rgb("signal-allow", "dark"),
        "between": b.rgb("text-confidential", "dark"),
        "refuse": b.rgb("signal-refuse", "dark"),
    }
    lines = [
        f"// {STAMP}",
        "//",
        "// The three level colours, from the dark theme text tokens, because a terminal is dark.",
        f"// allow is the lowest level ({low}), refuse is the highest ({high}) and the glyph colours",
        "// signal-allow and signal-refuse are aliases of those two, which is why a refusal is never",
        "// a fourth red. between carries every level in the middle.",
        "",
        "export type Paint = \"allow\" | \"between\" | \"refuse\" | \"dim\";",
        "",
        "export const RGB: Record<Exclude<Paint, \"dim\">, [number, number, number]> = {",
    ]
    for name, value in rgb.items():
        lines.append(f"  {name}: [{value[0]}, {value[1]}, {value[2]}],")
    lines += [
        "};",
        "",
        "/** The 4 bit fallback, for a terminal that does not report truecolor. */",
        "export const BASIC: Record<Exclude<Paint, \"dim\">, string> = {",
        '  allow: "\\x1b[32m",',
        '  between: "\\x1b[94m",',
        '  refuse: "\\x1b[31m",',
        "};",
        "",
    ]
    return "\n".join(lines)


def tokens_sh(b: Brand) -> str:
    """The band, for the launcher. The first frame of a live demo is a terminal."""
    lines = [
        f"# {STAMP}",
        "#",
        "# Band fills for a terminal, from the dark theme band tokens, because a terminal is",
        "# dark. BAND_RGB_<level> is 24 bit; BAND_BG_<level> is the 4 bit fallback, on the same",
        "# ordinal rule the status line uses: lowest green, highest red, everything between blue.",
        "",
    ]
    for i, level in enumerate(b.levels):
        basic = "42" if i == 0 else "41" if i == len(b.levels) - 1 else "44"
        lines.append(f'BAND_RGB_{level}="{";".join(str(c) for c in b.rgb(f"band-{level}", "dark"))}"')
        lines.append(f'BAND_BG_{level}="{basic}"')
    lines += [
        "",
        f'BAND_INK="{";".join(str(c) for c in b.rgb("band-ink", "dark"))}"',
        "",
        "# Providers cleared to read each level, lowest clearance first.",
    ]
    for level in b.levels:
        lines.append(f'CLEARED_{level}="{",".join(b.cleared(level))}"')
    return "\n".join(lines) + "\n"


def mplstyle(b: Brand) -> str:
    """Rules, not boxes: the notebook's charts on the same foundations as a slide."""
    # matplotlib treats # as a comment anywhere in an mplstyle line, so a colour written
    # as #fbfbf8 silently parses as empty and the whole file does nothing. Bare hex, as
    # in matplotlib's own matplotlibrc.
    hexes = lambda name: b.color(name).lstrip("#")
    out = [
        f"# {STAMP}",
        "#",
        "# There is no chart palette. The cycle is ink, because a chart that needs a fourth",
        "# colour is a chart with a fourth claim in it. A level colour is reached for by name",
        "# (design-system/tokens.py, COLOR['text-restricted']) when the line IS that level.",
        "",
        f"figure.facecolor: {hexes('paper-000')}",
        f"figure.edgecolor: {hexes('paper-000')}",
        f"savefig.facecolor: {hexes('paper-000')}",
        "figure.dpi: 110",
        "figure.autolayout: True",
        "",
        f"axes.facecolor: {hexes('paper-000')}",
        f"axes.edgecolor: {hexes('rule-200')}",
        f"axes.labelcolor: {hexes('ink-600')}",
        "axes.linewidth: 0.8",
        "axes.grid: True",
        "axes.spines.top: False",
        "axes.spines.right: False",
        "axes.titlesize: 13",
        "axes.titleweight: bold",
        f"axes.titlecolor: {hexes('ink-900')}",
        "axes.labelsize: 11",
        f"axes.prop_cycle: cycler('color', ['{hexes('ink-900')}', '{hexes('ink-600')}', '{hexes('ink-400')}'])",
        "",
        f"grid.color: {hexes('rule-200')}",
        "grid.linewidth: 0.6",
        "",
        f"text.color: {hexes('ink-900')}",
        f"xtick.color: {hexes('ink-400')}",
        f"ytick.color: {hexes('ink-400')}",
        f"xtick.labelcolor: {hexes('ink-600')}",
        f"ytick.labelcolor: {hexes('ink-600')}",
        "xtick.labelsize: 10",
        "ytick.labelsize: 10",
        "xtick.direction: out",
        "ytick.direction: out",
        "",
        "font.family: serif",
        f"font.serif: {b.font('doc-body')}, DejaVu Serif",
        f"font.monospace: {b.font('doc-code')}, DejaVu Sans Mono",
        "font.size: 11",
        "",
        "legend.frameon: False",
        f"legend.labelcolor: {hexes('ink-600')}",
        "lines.linewidth: 1.3",
        "",
        "image.cmap: gray",
    ]
    return "\n".join(out) + "\n"


def favicon(b: Brand) -> str:
    """The band, at 32px. No lock, no shield, no key: this is bookkeeping."""
    return (
        f'<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- {STAMP} -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" role="img" '
        f'aria-label="A public classification band">\n'
        f'  <rect width="32" height="32" fill="{b.color("paper-000")}"/>\n'
        f'  <rect width="32" height="9" fill="{b.color("band-public")}"/>\n'
        f'  <rect y="23" width="32" height="9" fill="{b.color("band-public")}"/>\n'
        f'  <rect x="5" y="14" width="22" height="3" fill="{b.color("ink-900")}"/>\n'
        f"</svg>\n"
    )


# ------------------------------------------------------------------- the cover art


def cover_svg(b: Brand, theme: str, level: str = "public", top: int = 0, height: int = 300) -> str:
    """The repository banner, with real text. flatten() turns it into outlines.

    The banner is 1280x300. A taller canvas (a negative `top`) is the same composition on
    more paper, for the social card, with the band still on the top edge of the image.
    """
    gutter = int(str(b.space["space-5"]).removesuffix("px"))
    right = 1280 - gutter
    band_h = 44
    band_size = b.px("cover-banner")
    tracking = round(band_size * 0.16, 2)

    # The band must not collide with itself. PT Mono advances 0.6em, plus the tracking.
    left_text, right_text = level.upper(), b.band_right(level)
    def band_width(text: str, size: float) -> float:
        return len(text) * (size * 0.6 + size * 0.16)
    size = band_size
    while size > 13 and band_width(left_text, size) + band_width(right_text, size) > (1280 - 2 * gutter - 24):
        size -= 0.5
    tracking = round(size * 0.16, 2)

    ladder = list(reversed(b.levels))  # highest at the top
    total = len(b.providers)
    unit = (right - 840) / max(total, 1)
    rows = []
    for i, lvl in enumerate(ladder):
        y = 103 + i * 52
        count = len(b.cleared(lvl))
        rows.append(
            f'  <rect x="840" y="{y}" width="{round(count * unit, 1)}" height="34" fill="{b.color(f"band-{lvl}", theme)}"/>\n'
            f'  <text x="853" y="{y + 23}" style="font-size:18px;font-family:\'{b.font("value")}\';'
            f'fill:{b.color("band-ink", theme)}">{lvl}</text>\n'
            f'  <text x="822" y="{y + 23}" style="font-size:18px;font-family:\'{b.font("value")}\';'
            f'text-anchor:end;fill:{b.color("ink-600", theme)}">{count} of {total}</text>'
        )

    alt = (
        "confidentiality-broker: access control for LLM agents. The folder carries a label, "
        "the provider carries a clearance, and the broker compares them on every tool call."
    )
    return (
        f'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
        f"<!-- {STAMP} -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="{height}"'
        f' viewBox="0 {top} 1280 {height}" role="img" aria-labelledby="t" version="1.1">\n'
        f"  <title id=\"t\">{alt}</title>\n"
        f'  <rect x="0" y="{top}" width="1280" height="{height}" fill="{b.color("paper-000", theme)}"/>\n'
        f'  <rect x="0" y="{top}" width="1280" height="{band_h}" fill="{b.color(f"band-{level}", theme)}"/>\n'
        f'  <text x="{gutter}" y="{top + 29}" style="font-size:{size}px;font-family:\'{b.font("cover-banner")}\';'
        f'letter-spacing:{tracking};fill:{b.color("band-ink", theme)}">{left_text}</text>\n'
        f'  <text x="{right}" y="{top + 29}" style="font-size:{size}px;font-family:\'{b.font("cover-banner")}\';'
        f'letter-spacing:{tracking};text-anchor:end;fill:{b.color("band-ink", theme)}">{right_text}</text>\n'
        f'  <text x="{gutter}" y="158" style="font-size:{b.px("cover-name")}px;'
        f'font-family:\'{b.font("cover-name")}\';fill:{b.color("ink-900", theme)}">confidentiality-broker</text>\n'
        f'  <text x="{gutter}" y="211" style="font-size:30px;font-family:\'{b.font("cover-tag")}\';'
        f'fill:{b.color("ink-600", theme)}">A label on the folder. A clearance on the provider.</text>\n'
        f'  <text x="{gutter}" y="248" style="font-size:19px;font-family:\'{b.font("value")}\';'
        f'fill:{b.color("ink-400", theme)}">compared on every tool call, in code, never in the prompt</text>\n'
        f'  <text x="840" y="88" style="font-size:14px;font-family:\'{b.font("label")}\';letter-spacing:2;'
        f'fill:{b.color("ink-400", theme)}">PROVIDERS CLEARED TO READ IT</text>\n' + "\n".join(rows) + "\n</svg>\n"
    )


def inkscape() -> str | None:
    return shutil.which("inkscape")


def _clean_env() -> dict:
    """Snap provided library paths break the system inkscape. Drop them for the child only."""
    env = dict(os.environ)
    for key in ("LD_LIBRARY_PATH", "GTK_PATH", "GIO_MODULE_DIR", "LOCPATH", "GDK_PIXBUF_MODULE_FILE"):
        env.pop(key, None)
    return env


def flatten(svg: str, out: Path) -> None:
    """Author with real text, then flatten: an SVG in an <img> cannot load a font."""
    binary = inkscape()
    if binary is None:
        raise RuntimeError("inkscape is not installed, so the cover text cannot be flattened to outlines")
    with tempfile.TemporaryDirectory() as tmp:
        raw = Path(tmp) / "raw.svg"
        raw.write_text(svg, encoding="utf-8")
        subprocess.run(
            [binary, str(raw), "--export-type=svg", "--export-text-to-path", "--export-plain-svg",
             f"--export-filename={out}"],
            check=True, env=_clean_env(), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
    text = out.read_text(encoding="utf-8")
    if "<text" in text:
        raise RuntimeError(f"{out} still has a <text> element, so a reader without PT Mono sees a fallback face")
    if not text.lstrip().startswith("<?xml"):
        text = '<?xml version="1.0" encoding="UTF-8" standalone="no"?>' + text
    out.write_text(text.replace("<svg", f"<!-- {STAMP} --><svg", 1), encoding="utf-8")


def social_png(b: Brand, out: Path) -> None:
    """1200x630 for og:image. A link to the deck should arrive marked."""
    binary = inkscape()
    if binary is None:
        raise RuntimeError("inkscape is not installed, so the social card cannot be rendered")
    # The same composition on a 1280x630 canvas: band on the top edge, content where it
    # sits on the banner, paper everywhere else. Exported at 1200 wide, which is the size
    # every link unfurler wants.
    card = cover_svg(b, "light", top=-165, height=630)
    with tempfile.TemporaryDirectory() as tmp:
        raw = Path(tmp) / "card.svg"
        raw.write_text(card, encoding="utf-8")
        subprocess.run(
            [binary, str(raw), "--export-type=png", "--export-width=1200", f"--export-filename={out}"],
            check=True, env=_clean_env(), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )


# ------------------------------------------------------- blocks inside handwritten files


def block(marker: str, body: str, comment: str = "html") -> tuple[str, str, str]:
    open_, close = {
        "html": (f"<!-- brand:{marker} -->", f"<!-- /brand:{marker} -->"),
        "css": (f"/* brand:{marker} */", f"/* /brand:{marker} */"),
    }[comment]
    return open_, close, body


def replace_block(text: str, open_: str, close: str, body: str) -> str:
    pattern = re.compile(re.escape(open_) + r".*?" + re.escape(close), re.S)
    if not pattern.search(text):
        raise RuntimeError(f"no {open_} block to fill")
    return pattern.sub(lambda _: f"{open_}\n{body}\n{close}", text, count=1)


def test_count() -> int:
    """The badge states a number, so the number is counted rather than remembered.

    node:test registers one test per top level test() call and the suite has no dynamic
    ones, so this is the figure `npm test` prints.
    """
    tests = (ROOT / ".pi" / "extensions" / "confidentiality-broker").glob("*.test.ts")
    return sum(len(re.findall(r"^\s*test\(", f.read_text(encoding="utf-8"), re.M)) for f in tests)


def readme_marking(b: Brand) -> str:
    """The marking line and the badges: facts on the level colours, never a shield that says nothing."""
    ink = "3C4048"
    badges = [
        ("tests", "tests", f"{test_count()}%20passing", b.color("band-public").lstrip("#").upper()),
        ("levels", "levels", str(len(b.levels)), b.color("band-confidential").lstrip("#").upper()),
        ("models", "models", "local%20or%20EU", ink),
        ("AaltoAI 2026", "AaltoAI%202026", "Norrin", b.color("ink-400").lstrip("#").upper()),
    ]
    lines = [b.marking("public"), ""]
    lines += [f"![{alt}](https://img.shields.io/badge/{label}-{value}-{hex_})" for alt, label, value, hex_ in badges]
    return "\n".join(lines)


def site_tokens(b: Brand) -> str:
    """The site ships one file, so its tokens are inlined rather than linked."""
    used = [
        "paper-000", "paper-100", "ink-900", "ink-600", "ink-400", "rule-200",
        "band-public", "band-ink", "text-public", "text-confidential", "text-restricted",
    ]
    return (
        "  :root{\n"
        + "\n".join(f"    --{n}:{b.color(n)};" for n in used)
        + f"\n    --font-serif:{b.families['serif']};"
        + f"\n    --font-mono:{b.families['mono']};"
        + "\n" + "\n".join(f"    --{n}:{v};" for n, v in b.space.items())
        + f"\n    --shadow-web:{b.shadow['shadow-web']};\n  }}\n"
        "  @media (prefers-color-scheme: dark){\n"
        '    :root:not([data-theme="light"]){\n'
        + "\n".join(f"      --{n}:{b.color(n, 'dark')};" for n in used)
        + "\n    }\n  }"
    )


def site_band(b: Brand, bottom: bool = False) -> str:
    right = "PAGE MARKED BY CONFIDENTIALITY-BROKER" if bottom else b.band_right("public")
    return (
        '  <div class="band">\n'
        "    <span>PUBLIC</span>\n"
        f'    <span class="cleared">{right}</span>\n'
        "  </div>"
    )


WORDS = ["no", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve"]


def spelled(n: int) -> str:
    """Prose counts are words. A number in prose reads as machine output, and this is prose."""
    return WORDS[n] if n < len(WORDS) else str(n)


def ds_marking_table(b: Brand) -> str:
    rows = [
        ("Nothing confidential (a mechanism diagram, the roadmap, the title)", "public"),
        ("A confidential path, filename or field name", "confidential"),
        ("Anything from the health workspace", "restricted"),
    ]
    out = ["| The page shows | Band | Fill token |", "| --- | --- | --- |"]
    for shows, level in rows:
        if level not in b.levels:
            continue
        n = len(b.cleared(level))
        out.append(f"| {shows} | `{level.upper()}` and the {spelled(n)} cleared providers | `band-{level}` |")
    return "\n".join(out)


def demo_workspace_table(b: Brand) -> str:
    out = ["| Workspace | Label | Providers cleared |", "|---|---|---|"]
    for path, level in b.workspaces():
        out.append(f"| `{path}` | `{level}` | {', '.join(b.cleared(level))} |")
    return "\n".join(out)


# ----------------------------------------------------------------------- the targets


def surfaces(b: Brand) -> list[tuple[Path, str]]:
    """Whole files this script owns."""
    return [
        (ROOT / "design-system" / "tokens.css", tokens_css(b)),
        (ROOT / "design-system" / "tokens.py", tokens_py(b)),
        (ROOT / "design-system" / "tokens.sh", tokens_sh(b)),
        (ROOT / "design-system" / "marked.mplstyle", mplstyle(b)),
        (ROOT / ".pi" / "extensions" / "confidentiality-broker" / "brand.generated.ts", brand_ts(b)),
        (ROOT / "site" / "favicon.svg", favicon(b)),
    ]


#: Every page we author carries its marking above its title. The repository is public,
#: so the line reads PUBLIC even where the page discusses a confidential workspace, as
#: design-system/guidelines/30-github-cover.md says. docs/challenge.md is the sponsor's
#: brief, quoted rather than written here, so it is left exactly as it arrived.
MARKED_PAGES = [
    (".github", "PULL_REQUEST_TEMPLATE.md"),
    (".pi", "extensions", "confidentiality-broker", "README.md"),
    ("demo", "README.md"),
    ("design-system", "README.md"),
    ("docs", "decisions.md"),
    ("docs", "cloud-setup.md"),
]


def blocks(b: Brand) -> list[tuple[Path, str, str, str]]:
    """Regions this script owns inside files a person writes."""
    return [
        (ROOT / "README.md", *block("marking", readme_marking(b))),
        *((ROOT.joinpath(*page), *block("marking", b.marking("public"))) for page in MARKED_PAGES),
        (ROOT / "site" / "index.html", *block("tokens", site_tokens(b), "css")),
        (ROOT / "site" / "index.html", *block("band-top", site_band(b))),
        (ROOT / "site" / "index.html", *block("band-bottom", site_band(b, bottom=True))),
        (ROOT / "design-system" / "README.md", *block("marking-table", ds_marking_table(b))),
        (ROOT / "demo" / "DEMO.md", *block("workspaces", demo_workspace_table(b))),
    ]


def run(check: bool) -> int:
    b = load()
    stale: list[str] = []
    wrote: list[str] = []

    for path, content in surfaces(b):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            wrote.append(path.relative_to(ROOT).as_posix())

    unmarked: list[str] = []
    for path, open_, close, body in blocks(b):
        if not path.exists():
            stale.append(f"{path.relative_to(ROOT).as_posix()} (missing)")
            continue
        current = path.read_text(encoding="utf-8")
        try:
            updated = replace_block(current, open_, close, body)
        except RuntimeError:
            unmarked.append(f"{path.relative_to(ROOT).as_posix()} has no {open_} block yet")
            continue
        if updated == current:
            continue
        if check:
            stale.append(f"{path.relative_to(ROOT).as_posix()} [{open_}]")
        else:
            path.write_text(updated, encoding="utf-8")
            wrote.append(f"{path.relative_to(ROOT).as_posix()} [{open_}]")

    covers = [(ROOT / "docs" / "cover-light.svg", "light"), (ROOT / "docs" / "cover-dark.svg", "dark")]
    card = ROOT / "site" / "social-card.png"
    if inkscape() is None:
        print("brand: inkscape is not installed, so the covers and the social card were skipped", file=sys.stderr)
    elif check:
        # Regenerating an SVG is not byte stable across inkscape versions, so check the
        # facts the cover states rather than its bytes: the provider count in the ladder.
        for path, _ in covers:
            if not path.exists():
                stale.append(f"{path.relative_to(ROOT).as_posix()} (missing)")
                continue
            text = path.read_text(encoding="utf-8")
            expected = f"{len(b.cleared(b.levels[0]))} of {len(b.providers)}"
            if expected.replace(" ", "") not in re.sub(r"\s+", "", "".join(re.findall(r'aria-label="([^"]*)"', text))):
                stale.append(f"{path.relative_to(ROOT).as_posix()} (the clearance ladder does not match the policy)")
        if not card.exists():
            stale.append("site/social-card.png (missing)")
    else:
        for path, theme in covers:
            flatten(cover_svg(b, theme), path)
            wrote.append(path.relative_to(ROOT).as_posix())
        social_png(b, card)
        wrote.append(card.relative_to(ROOT).as_posix())

    for note in unmarked:
        print(f"brand: {note}", file=sys.stderr)

    if check:
        if stale:
            print("brand: out of date, run python3 scripts/brand.py", file=sys.stderr)
            for name in stale:
                print(f"  {name}", file=sys.stderr)
            return 1
        print("brand: every marked surface matches tokens.json and .pi/confidentiality.json")
        return 0

    for name in wrote:
        print(f"brand: wrote {name}")
    if not wrote:
        print("brand: nothing to do, every marked surface was already current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if a generated surface is out of date")
    parser.add_argument("--list", action="store_true", help="print what this script owns")
    args = parser.parse_args()

    if args.list:
        b = load()
        for path, _ in surfaces(b):
            print(path.relative_to(ROOT).as_posix())
        for path, open_, _, _ in blocks(b):
            print(f"{path.relative_to(ROOT).as_posix()} {open_}")
        print("docs/cover-light.svg\ndocs/cover-dark.svg\nsite/social-card.png")
        return 0
    return run(args.check)


if __name__ == "__main__":
    sys.exit(main())
