"""Generated by scripts/brand.py from design-system/tokens.json and .pi/confidentiality.json. Do not edit."""

LEVELS = ["public", "confidential", "restricted"]
PROVIDERS = {
    "google": "public",
    "openai": "public",
    "mistral": "confidential",
    "lemonade": "restricted",
    "ollama": "restricted",
    "verda": "confidential"
}

COLOR = {
    "paper-000": {
        "light": "#fbfbf8",
        "dark": "#0e1116"
    },
    "paper-100": {
        "light": "#f1f1ec",
        "dark": "#151a21"
    },
    "ink-900": {
        "light": "#0e0e0e",
        "dark": "#eef1f4"
    },
    "ink-600": {
        "light": "#5a5a5a",
        "dark": "#9aa3ad"
    },
    "ink-400": {
        "light": "#8c8c8c",
        "dark": "#6f7883"
    },
    "rule-200": {
        "light": "#d8d8d2",
        "dark": "#263039"
    },
    "band-public": {
        "light": "#00703c",
        "dark": "#0a7a44"
    },
    "band-confidential": {
        "light": "#0b3d91",
        "dark": "#1d4fa3"
    },
    "band-restricted": {
        "light": "#c8102e",
        "dark": "#d21b34"
    },
    "band-ink": {
        "light": "#ffffff",
        "dark": "#ffffff"
    },
    "text-public": {
        "light": "#00703c",
        "dark": "#4fc98a"
    },
    "text-confidential": {
        "light": "#0b3d91",
        "dark": "#7aa7f0"
    },
    "text-restricted": {
        "light": "#c8102e",
        "dark": "#ff7f8f"
    },
    "signal-refuse": {
        "light": "#c8102e",
        "dark": "#ff7f8f"
    },
    "signal-allow": {
        "light": "#00703c",
        "dark": "#4fc98a"
    }
}

SPACE = {
    "space-1": "6px",
    "space-2": "12px",
    "space-3": "18px",
    "space-4": "26px",
    "space-5": "38px",
    "space-6": "58px"
}

#: Providers cleared to read each level, lowest clearance first.
CLEARED = {
    "public": [
        "google",
        "openai",
        "mistral",
        "verda",
        "lemonade",
        "ollama"
    ],
    "confidential": [
        "mistral",
        "verda",
        "lemonade",
        "ollama"
    ],
    "restricted": [
        "lemonade",
        "ollama"
    ]
}

#: The marking line a generated document carries.
MARKING = {
    "public": "`PUBLIC` \u00b7 cleared: google, openai, mistral, verda, lemonade, ollama",
    "confidential": "`CONFIDENTIAL` \u00b7 cleared: mistral, verda, lemonade, ollama",
    "restricted": "`RESTRICTED` \u00b7 cleared: lemonade, ollama"
}

#: Terminal truecolor for a level, from the dark theme text tokens.
LEVEL_RGB = {
    "public": [
        79,
        201,
        138
    ],
    "confidential": [
        122,
        167,
        240
    ],
    "restricted": [
        255,
        127,
        143
    ]
}


def marking(level: str) -> str:
    """The marking line for a level, or a refusal to mark a level the policy does not know."""
    if level not in MARKING:
        raise ValueError(f"{level!r} is not a level in .pi/confidentiality.json: {LEVELS}")
    return MARKING[level]
