# Generated by scripts/brand.py from design-system/tokens.json and .pi/confidentiality.json. Do not edit.
#
# Band fills for a terminal, from the dark theme band tokens, because a terminal is
# dark. BAND_RGB_<level> is 24 bit; BAND_BG_<level> is the 4 bit fallback, on the same
# ordinal rule the status line uses: lowest green, highest red, everything between blue.

BAND_RGB_public="10;122;68"
BAND_BG_public="42"
BAND_RGB_confidential="29;79;163"
BAND_BG_confidential="44"
BAND_RGB_restricted="210;27;52"
BAND_BG_restricted="41"

BAND_INK="255;255;255"

# Providers cleared to read each level, lowest clearance first.
CLEARED_public="google,openai,mistral,verda,lemonade,ollama"
CLEARED_confidential="mistral,verda,lemonade,ollama"
CLEARED_restricted="lemonade,ollama"
